### ISSUE TITLE
MAMa.py library is missing.

### ISSUE THREAD

**Issue by icemduru** [meb-team/plasmidome_scripts#1]
Hi,

There are two issues with PlasSuite/bin/MAMa.py.

shebang is defined as '#!/home/chochart/miniconda3/bin/python' therefore the program gives an error. It is easy for the user to fix. However there is another problem:

The MAMa library location is hard coded in the code, which is:
dir_module = '/data/chochart/lib/'

This causes the error:
from MAMa import version
ImportError: cannot import name 'version'

Could you please share the library ? or if it is shared could you please tell the location ?

**Comment by chochart** [comment]
Hi @icemduru , 

Sorry for the delay. Only a part of the code of the MAMa package local on our server has been copied in PlasSuite repository explaining the error. 
PlasSuite call now the public [BAM-Tk](https://github.com/meb-team/BAM-Tk#installation) (formerly MAMa) python package.

**Comment by icemduru** [comment]
Hi, 

Thanks a lot !! Now it works.

Couple more observation:
MAPme requires picard.jar to work. And it is written hard-coded in the code (line 127):
https://github.com/meb-team/PlasSuite/blob/ef9902d7c8e679102e3330c392c7241eccd14205/bin/MAPme#L127
I believe it would be good to have in readme section of PlasAbund.


And I needed to change the deliminator comma to tab in line 11 of sum_resistance_matrix.py, otherwise it was giving an error.
https://github.com/meb-team/PlasSuite/blob/ef9902d7c8e679102e3330c392c7241eccd14205/bin/sum_resistance_matrix.py#L11
I do not know is it a general problem, however I wanted to share my observation.

**Comment by chochart** [comment]
> MAPme requires picard.jar to work. And it is written hard-coded in the code (line 127)

Yes indeed. I noticed this last time. It's fixed. I added an argument to allow changing the file path and some details in the readme section as you suggested. 

> And I needed to change the deliminator comma to tab in line 11 of sum_resistance_matrix.py, otherwise it was giving an error.

Oh yes my bad. It's now fixed! 

Thanks a lot for the feedback!
