### ISSUE TITLE
Not available of the data

### ISSUE THREAD

**Issue by yuqing-feng** [meb-team/plasmidome_scripts#3]
I am not sure about whether or not it is an issue about the internet of mine that I could note get the data from the following :
https://s3.mesocentre.uca.fr/swift/v1/AUTH_f70cfb776e144d419461999459de06fb/PlasSuite/plasmidome_databases.tar.gz

**Comment by debroas** [comment]
Hello,
There is some issues with this public link. 
Try **wget https://s3.mesocentre.uca.fr/PlasSuite/plasmidome_databases.tar.gz**
Sincerely

**Comment by yuqing-feng** [comment]
Thank you for your reply.
