### ISSUE TITLE
Database 404

### ISSUE THREAD

**Issue by Orin-beep** [meb-team/plasmidome_scripts#4]
The database at  https://s3.mesocentre.uca.fr/swift/v1/AUTH_f70cfb776e144d419461999459de06fb/PlasSuite/plasmidome_databases.tar.gz
cannot be downloaded. Thanks very much.

**Comment by debroas** [comment]
Hello,

Thank you for your feedback
Try wget https://s3.mesocentre.uca.fr/PlasSuite/plasmidome_databases.tar.gz
Sincerely

**Comment by Orin-beep** [comment]
Got it. The link works now. Many thanks!
